---
include:
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view_gem #updated entry
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view_gem #updated entry
